version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./refactored/Dockerfile
    ports:
      - "8080:8080"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      LLM_PROVIDER: openai
      OPENAI_MODEL: gpt-4-turbo
      INITIAL_ARTICLE_URLS: "https://techcrunch.com/2025/07/26/tesla-vet-says-that-reviewing-real-products-not-mockups-is-the-key-to-staying-innovative/"
    volumes:
      - .:/app
    working_dir: /root/

  # We are not using a database for the refactored version (in-memory sync.Map)
  # If a database becomes necessary, it can be added here.
